import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';

function home() {
  window.document.title = "Home | Py-bot.cf"
  return (
    <div className="container" style={{ minHeight: "80vh", paddingTop: "15px" }}>
      <h1 style={{ textAlign: "center", fontWeight: "200" }}>
        Hello Cruel World!
      </h1>

      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id scelerisque sem. Curabitur interdum, libero sed auctor varius, neque nisi tincidunt nisl, eget ornare tellus massa quis libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas sed feugiat magna, ac sollicitudin eros. Curabitur sed nulla non ipsum rhoncus efficitur. Suspendisse scelerisque odio ut mi lacinia pulvinar. Pellentesque felis velit, pellentesque a tincidunt vel, tempus et ligula. Curabitur interdum enim sem, ac ornare orci rhoncus sit amet. Vivamus quis sodales erat, et dapibus libero. Nullam id nisi quam. Praesent nisl est, congue at turpis eget, tincidunt pharetra mauris. Proin volutpat augue eu nulla scelerisque dignissim. Sed lobortis, risus sit amet venenatis luctus, leo eros vestibulum velit, non hendrerit massa leo vel massa.
        <br/> <br/>
        Maecenas tempor, ipsum sed auctor convallis, quam dui cursus dolor, at dictum dui enim id ex. Aenean eu tortor in ante efficitur egestas. Proin dignissim purus vitae eros pellentesque varius. Donec consectetur ullamcorper sem, in vulputate tortor suscipit vel. In hac habitasse platea dictumst. Maecenas tempor tempus felis ac placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent gravida faucibus sagittis. Donec consectetur dolor in risus semper, eu consequat risus dapibus. Cras ultrices vestibulum sem nec accumsan. Nam tincidunt porttitor metus, et lacinia leo viverra non. Aenean dapibus eu turpis a ullamcorper. Morbi risus lorem, condimentum ac magna quis, tincidunt facilisis arcu. Nam fermentum id libero eget tristique. Suspendisse vestibulum pellentesque lorem a sollicitudin. Vivamus ut dolor libero.
        <br/> <br/>
        Sed aliquet ex dui, sed viverra dolor vestibulum a. Donec laoreet dignissim leo, quis sollicitudin augue gravida a. Sed iaculis mi varius interdum viverra. Donec aliquam eros eget mollis ornare. Nullam eget tincidunt elit. Phasellus malesuada ornare mauris sed commodo. Vivamus in ex nunc. Curabitur sed quam purus. Sed pellentesque leo quis lacus ultricies condimentum. Morbi tristique scelerisque fermentum. Nam varius, eros a dignissim imperdiet, libero lorem lacinia justo, non molestie nunc leo in elit. Donec non viverra nulla. Vivamus vel auctor purus, ut pellentesque nibh. Suspendisse non ultrices mauris.
        <br/> <br/>
        Cras et nibh mattis, maximus nulla id, viverra nunc. Suspendisse dolor mi, imperdiet non risus ut, rutrum consequat urna. Mauris sed lobortis nisi, sit amet varius nibh. Pellentesque justo ligula, convallis vel dolor at, ultricies elementum libero. Vivamus erat dui, blandit tincidunt erat non, sollicitudin rutrum libero. Nulla blandit elit vitae purus imperdiet molestie et ac lorem. Vestibulum tristique luctus arcu in placerat. Maecenas dui arcu, dignissim sed lorem non, consequat scelerisque nulla. Praesent dapibus felis imperdiet, placerat felis vel, venenatis dui. Vestibulum ut ipsum pretium, pellentesque justo ut, pulvinar diam.
        <br/> <br/>
        Mauris volutpat tellus eu posuere tristique. Duis ante urna, dignissim sed ornare vitae, pellentesque quis erat. Curabitur consectetur nulla ante, nec cursus tellus lacinia nec. Vivamus semper ullamcorper felis, quis bibendum mi vehicula ut. Suspendisse molestie scelerisque quam, porta consequat nisi gravida ac. Donec quis mollis massa, at rhoncus tortor. Proin sodales molestie nisi, ac ullamcorper nulla tristique nec. Aliquam dapibus nulla dui, at faucibus quam tincidunt semper. Aliquam ut cursus massa. Etiam suscipit convallis quam, vel dignissim neque scelerisque ac. Ut at urna et nibh consequat ultrices eu id nulla. Nunc tellus urna, bibendum vulputate ornare nec, lacinia ut leo.
        <br/> <br/>
        Nunc dictum facilisis lacus, sed congue massa condimentum ut. Donec ac nulla euismod, dictum enim non, venenatis lectus. Fusce nec enim orci. Sed consectetur semper magna ut elementum. Duis a urna commodo, molestie nisl ut, tincidunt sapien. Praesent blandit lectus nec sem maximus rhoncus vitae id lorem. Sed a risus accumsan, molestie leo a, blandit mi. Duis ac eleifend mi. Fusce aliquet, orci vitae porta vehicula, sem mauris imperdiet odio, a dictum lorem enim efficitur massa. Integer bibendum orci sit amet sapien gravida sagittis. Ut eros augue, venenatis in nisi at, aliquam ultrices eros. In non erat tortor. Mauris non diam pellentesque, tincidunt nunc placerat, feugiat lacus. Donec elementum lorem ullamcorper fringilla vehicula.
        <br/> <br/>
        Sed volutpat ipsum eget fermentum tincidunt. Aenean eget nunc eu nibh tincidunt dictum sit amet sit amet dolor. Praesent condimentum dapibus magna, sit amet vestibulum lacus aliquet non. Fusce erat risus, ultricies vitae est vel, fringilla laoreet elit. Donec ut magna ullamcorper, porttitor odio vitae, semper orci. Proin semper faucibus neque, in sollicitudin justo molestie nec. Cras nisi massa, pretium sit amet pharetra eu, auctor nec ex. Quisque semper pulvinar sagittis. In eget lacus sit amet urna scelerisque dignissim. Donec convallis tincidunt augue, ac viverra elit. Nunc hendrerit efficitur tempus. Phasellus accumsan non dolor vel tempus. Integer interdum quam vitae ullamcorper mollis.
        <br/> <br/>
        Proin eu ultrices est, eget ultricies nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras sit amet neque volutpat, efficitur nulla sit amet, aliquet diam. Vivamus tempus, dolor eu tincidunt vestibulum, est turpis varius lacus, nec gravida sapien mauris a metus. Nunc gravida nulla eu odio faucibus, nec tincidunt nisl tempus. Pellentesque nec ex eleifend, varius eros in, viverra neque. Vestibulum in ultricies sapien. Proin et cursus arcu. Suspendisse eget sapien vitae ante convallis consequat ac id turpis. In hac habitasse platea dictumst. Maecenas consectetur lacinia magna vitae porta. Duis lobortis, magna non vehicula aliquet, ante sem interdum augue, in blandit mauris nibh at enim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eu faucibus eros. Nam urna erat, tincidunt nec ex tincidunt, mattis vehicula nibh. Integer non tellus lorem.
        <br/> <br/>
        Duis sollicitudin odio vitae arcu luctus accumsan. Cras vehicula luctus justo, a fringilla tortor. Nam vel commodo augue. Maecenas eu diam tincidunt augue convallis aliquet. Duis quis pharetra quam. Nunc condimentum velit malesuada, mattis nunc sit amet, congue mi. Curabitur mi tellus, mattis feugiat eleifend eu, placerat vitae nunc. Vestibulum ultricies nibh diam, sed feugiat justo fermentum eget. Phasellus pharetra accumsan sodales. Maecenas hendrerit ante finibus, facilisis lorem in, molestie tortor. Duis ut dui in risus pretium molestie. Etiam vel ligula a risus porttitor dignissim.
        <br/> <br/>
        Suspendisse pretium at lacus eu venenatis. Proin auctor eget erat vitae hendrerit. Sed purus sapien, elementum eu justo ut, imperdiet gravida felis. Vestibulum felis mi, laoreet eu elit vel, consectetur pulvinar neque. Curabitur molestie, felis eu vestibulum efficitur, massa dolor luctus ligula, vitae molestie dolor metus ac turpis. In sagittis turpis cursus, maximus mauris id, fermentum elit. Aliquam condimentum, metus ut molestie blandit, velit purus ornare urna, quis condimentum ipsum turpis ut tellus. Suspendisse egestas metus vel ipsum aliquam, eget fermentum odio consectetur. Donec velit massa, sodales eu mollis eu, hendrerit ut libero. Vestibulum fringilla leo id sem tempus blandit. Nulla porttitor leo a lectus bibendum, sit amet convallis magna placerat. Etiam quis orci libero. Curabitur urna massa, bibendum non auctor nec, tempus quis sapien.
      </p>
    </div>
  );
}

export default home;
