name: Push And Deploy

on:
  push:
    branches: [ bot ]
    
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploys
      uses: appleboy/ssh-action@master
      with:
        host: 129.159.201.52
        username: ubuntu
        key: ${{ secrets.CONSOLE_KEY }}
        port: 22
        script: |
          pip3 remove pycord
          ./update.sh
